-- MySQL Script generated by MySQL Workbench
-- Ter 18 Abr 2017 19:01:45 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cine` DEFAULT CHARACTER SET utf8 ;
USE `cine` ;

-- -----------------------------------------------------
-- Table `cine`.`sessoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine`.`sessoes` (
  `numeroDaSessao` INT NOT NULL AUTO_INCREMENT,
  `codFilme` VARCHAR(4) NOT NULL,
  `dataDaSessao` VARCHAR(45) NOT NULL,
  `numSala` VARCHAR(2) NOT NULL,
  `horario` VARCHAR(2) NOT NULL,
  `ingressosVendidos` VARCHAR(45) NOT NULL,
  `rendaObtida` FLOAT NOT NULL,
  PRIMARY KEY (`numeroDaSessao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cine`.`filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine`.`filmes` (
  `codFilme` VARCHAR(4) NOT NULL,
  `nomeFilme` VARCHAR(30) NOT NULL,
  `dataInicial` VARCHAR(45) NOT NULL,
  `dataFinal` VARCHAR(45) NOT NULL,
  `qtdMeiasEntradas` INT NOT NULL,
  `qtdInteira` INT NOT NULL,
  `rendaObtida` FLOAT NOT NULL,
  PRIMARY KEY (`codFilme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cine`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine`.`salas` (
  `numSala` VARCHAR(2) NOT NULL,
  `capacidadeDaSala` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`numSala`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
